databases:
  - name: law_project
    databaseName: law_project
    user: law_project

services:
  - type: web
    name: law_project
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn law_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: law_project
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4